/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Agent Attacker API
 * 网络安全渗透测试Agent API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { attacker_agent_api } from '../utils/attacker-agent-api';
/**
 * 响应数据
 */
export type ApiResponseUserCleanupResponseData = UserCleanupResponse | null;

export interface ApiResponseUserCleanupResponse {
  /** 业务状态码，非HTTP状态码 */
  code?: number;
  /** 响应消息 */
  message?: string;
  /** 响应数据 */
  data?: ApiResponseUserCleanupResponseData;
}

/**
 * 响应数据
 */
export type ApiResponseUserInitResponseData = UserInitResponse | null;

export interface ApiResponseUserInitResponse {
  /** 业务状态码，非HTTP状态码 */
  code?: number;
  /** 响应消息 */
  message?: string;
  /** 响应数据 */
  data?: ApiResponseUserInitResponseData;
}

/**
 * 响应数据
 */
export type ApiResponseUserStatusResponseData = UserStatusResponse | null;

export interface ApiResponseUserStatusResponse {
  /** 业务状态码，非HTTP状态码 */
  code?: number;
  /** 响应消息 */
  message?: string;
  /** 响应数据 */
  data?: ApiResponseUserStatusResponseData;
}

export type ChatRequestCustomInfoAnyOf = { [key: string]: unknown };

/**
 * 用户自定义信息，前端可自行填写任意键值对
 */
export type ChatRequestCustomInfo = ChatRequestCustomInfoAnyOf | null;

export interface ChatRequest {
  /** 用户ID */
  user_id: string;
  /** 消息内容 */
  message: string;
  /** 用户自定义信息，前端可自行填写任意键值对 */
  custom_info?: ChatRequestCustomInfo;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface LogRequest {
  /** 用户ID */
  user_id: string;
}

export interface UserCleanupResponse {
  /** 用户ID */
  user_id: string;
  /** 清理状态 */
  status: string;
  /** 清理时间 */
  cleaned_at: string;
}

export interface UserInitRequest {
  /** 用户ID */
  user_id: string;
  /** API密钥 */
  api_key: string;
}

export interface UserInitResponse {
  /** 用户ID */
  user_id: string;
  /** 初始化状态 */
  status: string;
  /** 创建时间 */
  created_at: string;
}

/**
 * 最后活动时间
 */
export type UserStatusResponseLastActivity = string | null;

export interface UserStatusResponse {
  /** 用户ID */
  user_id: string;
  /** 是否已初始化 */
  initialized: boolean;
  /** 最后活动时间 */
  last_activity?: UserStatusResponseLastActivity;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetUserStatusV1UserStatusGetParams = {
/**
 * 用户ID
 */
user_id: string;
};

export type CleanupUserV1UserCleanupDeleteParams = {
/**
 * 用户ID
 */
user_id: string;
};

/**
 * 为用户分配独立的Agent资源并初始化会话
 * @summary 初始化用户会话
 */
export const initUserV1UserInitPost = (
    userInitRequest: UserInitRequest,
 signal?: AbortSignal
) => {
      
      
      return attacker_agent_api<ApiResponseUserInitResponse>(
      {url: `/v1/user/init`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userInitRequest, signal
    },
      );
    }
  


export const getInitUserV1UserInitPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initUserV1UserInitPost>>, TError,{data: UserInitRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof initUserV1UserInitPost>>, TError,{data: UserInitRequest}, TContext> => {

const mutationKey = ['initUserV1UserInitPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof initUserV1UserInitPost>>, {data: UserInitRequest}> = (props) => {
          const {data} = props ?? {};

          return  initUserV1UserInitPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InitUserV1UserInitPostMutationResult = NonNullable<Awaited<ReturnType<typeof initUserV1UserInitPost>>>
    export type InitUserV1UserInitPostMutationBody = UserInitRequest
    export type InitUserV1UserInitPostMutationError = HTTPValidationError

    /**
 * @summary 初始化用户会话
 */
export const useInitUserV1UserInitPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof initUserV1UserInitPost>>, TError,{data: UserInitRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof initUserV1UserInitPost>>,
        TError,
        {data: UserInitRequest},
        TContext
      > => {

      const mutationOptions = getInitUserV1UserInitPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * 检查指定用户的Agent会话是否已初始化
 * @summary 检查用户会话状态
 */
export const getUserStatusV1UserStatusGet = (
    params: GetUserStatusV1UserStatusGetParams,
 signal?: AbortSignal
) => {
      
      
      return attacker_agent_api<ApiResponseUserStatusResponse>(
      {url: `/v1/user/status`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetUserStatusV1UserStatusGetQueryKey = (params: GetUserStatusV1UserStatusGetParams,) => {
    return [`/v1/user/status`, ...(params ? [params]: [])] as const;
    }

    
export const getGetUserStatusV1UserStatusGetQueryOptions = <TData = Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError = HTTPValidationError>(params: GetUserStatusV1UserStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserStatusV1UserStatusGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>> = ({ signal }) => getUserStatusV1UserStatusGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserStatusV1UserStatusGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>>
export type GetUserStatusV1UserStatusGetQueryError = HTTPValidationError


export function useGetUserStatusV1UserStatusGet<TData = Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError = HTTPValidationError>(
 params: GetUserStatusV1UserStatusGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserStatusV1UserStatusGet<TData = Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError = HTTPValidationError>(
 params: GetUserStatusV1UserStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>,
          TError,
          Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserStatusV1UserStatusGet<TData = Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError = HTTPValidationError>(
 params: GetUserStatusV1UserStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 检查用户会话状态
 */

export function useGetUserStatusV1UserStatusGet<TData = Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError = HTTPValidationError>(
 params: GetUserStatusV1UserStatusGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatusV1UserStatusGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserStatusV1UserStatusGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 清理指定用户的会话资源，释放Agent实例
 * @summary 清理用户会话资源
 */
export const cleanupUserV1UserCleanupDelete = (
    params: CleanupUserV1UserCleanupDeleteParams,
 ) => {
      
      
      return attacker_agent_api<ApiResponseUserCleanupResponse>(
      {url: `/v1/user/cleanup`, method: 'DELETE',
        params
    },
      );
    }
  


export const getCleanupUserV1UserCleanupDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cleanupUserV1UserCleanupDelete>>, TError,{params: CleanupUserV1UserCleanupDeleteParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof cleanupUserV1UserCleanupDelete>>, TError,{params: CleanupUserV1UserCleanupDeleteParams}, TContext> => {

const mutationKey = ['cleanupUserV1UserCleanupDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof cleanupUserV1UserCleanupDelete>>, {params: CleanupUserV1UserCleanupDeleteParams}> = (props) => {
          const {params} = props ?? {};

          return  cleanupUserV1UserCleanupDelete(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CleanupUserV1UserCleanupDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof cleanupUserV1UserCleanupDelete>>>
    
    export type CleanupUserV1UserCleanupDeleteMutationError = HTTPValidationError

    /**
 * @summary 清理用户会话资源
 */
export const useCleanupUserV1UserCleanupDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof cleanupUserV1UserCleanupDelete>>, TError,{params: CleanupUserV1UserCleanupDeleteParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof cleanupUserV1UserCleanupDelete>>,
        TError,
        {params: CleanupUserV1UserCleanupDeleteParams},
        TContext
      > => {

      const mutationOptions = getCleanupUserV1UserCleanupDeleteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * 发送消息给指定用户的Agent并获取流式响应，符合Server-Sent Events标准
 * @summary 发送消息给指定用户的Agent
 */
export const chatCompletionsV1ChatCompletionsPost = (
    chatRequest: ChatRequest,
 signal?: AbortSignal
) => {
      
      
      return attacker_agent_api<unknown>(
      {url: `/v1/chat/completions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: chatRequest, signal
    },
      );
    }
  


export const getChatCompletionsV1ChatCompletionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatCompletionsV1ChatCompletionsPost>>, TError,{data: ChatRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof chatCompletionsV1ChatCompletionsPost>>, TError,{data: ChatRequest}, TContext> => {

const mutationKey = ['chatCompletionsV1ChatCompletionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof chatCompletionsV1ChatCompletionsPost>>, {data: ChatRequest}> = (props) => {
          const {data} = props ?? {};

          return  chatCompletionsV1ChatCompletionsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ChatCompletionsV1ChatCompletionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof chatCompletionsV1ChatCompletionsPost>>>
    export type ChatCompletionsV1ChatCompletionsPostMutationBody = ChatRequest
    export type ChatCompletionsV1ChatCompletionsPostMutationError = HTTPValidationError

    /**
 * @summary 发送消息给指定用户的Agent
 */
export const useChatCompletionsV1ChatCompletionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof chatCompletionsV1ChatCompletionsPost>>, TError,{data: ChatRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof chatCompletionsV1ChatCompletionsPost>>,
        TError,
        {data: ChatRequest},
        TContext
      > => {

      const mutationOptions = getChatCompletionsV1ChatCompletionsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * 获取指定用户的日志信息并返回流式响应，符合Server-Sent Events标准
 * @summary 获取指定用户的日志信息
 */
export const getUserLogsV1LogsLogCompletionsPost = (
    logRequest: LogRequest,
 signal?: AbortSignal
) => {
      
      
      return attacker_agent_api<unknown>(
      {url: `/v1/logs/log/completions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logRequest, signal
    },
      );
    }
  


export const getGetUserLogsV1LogsLogCompletionsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserLogsV1LogsLogCompletionsPost>>, TError,{data: LogRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getUserLogsV1LogsLogCompletionsPost>>, TError,{data: LogRequest}, TContext> => {

const mutationKey = ['getUserLogsV1LogsLogCompletionsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getUserLogsV1LogsLogCompletionsPost>>, {data: LogRequest}> = (props) => {
          const {data} = props ?? {};

          return  getUserLogsV1LogsLogCompletionsPost(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetUserLogsV1LogsLogCompletionsPostMutationResult = NonNullable<Awaited<ReturnType<typeof getUserLogsV1LogsLogCompletionsPost>>>
    export type GetUserLogsV1LogsLogCompletionsPostMutationBody = LogRequest
    export type GetUserLogsV1LogsLogCompletionsPostMutationError = HTTPValidationError

    /**
 * @summary 获取指定用户的日志信息
 */
export const useGetUserLogsV1LogsLogCompletionsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getUserLogsV1LogsLogCompletionsPost>>, TError,{data: LogRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getUserLogsV1LogsLogCompletionsPost>>,
        TError,
        {data: LogRequest},
        TContext
      > => {

      const mutationOptions = getGetUserLogsV1LogsLogCompletionsPostMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * 根路径
 * @summary Root
 */
export const rootGet = (
    
 signal?: AbortSignal
) => {
      
      
      return attacker_agent_api<unknown>(
      {url: `/`, method: 'GET', signal
    },
      );
    }
  

export const getRootGetQueryKey = () => {
    return [`/`] as const;
    }

    
export const getRootGetQueryOptions = <TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRootGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({ signal }) => rootGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RootGetQueryResult = NonNullable<Awaited<ReturnType<typeof rootGet>>>
export type RootGetQueryError = unknown


export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Root
 */

export function useRootGet<TData = Awaited<ReturnType<typeof rootGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRootGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * 健康检查
 * @summary Health
 */
export const healthHealthGet = (
    
 signal?: AbortSignal
) => {
      
      
      return attacker_agent_api<unknown>(
      {url: `/health`, method: 'GET', signal
    },
      );
    }
  

export const getHealthHealthGetQueryKey = () => {
    return [`/health`] as const;
    }

    
export const getHealthHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthHealthGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({ signal }) => healthHealthGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = unknown


export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthHealthGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
